# This workflow will build an Arch Linux ISO file with the commit on it
name: build parchiso per release
on:
  release:
    types:
      - created

env:
  api_key: ${{ secrets.GITHUB_TOKEN }}
  name: ${{ github.event.repository.name }}
  release_name: ${{ github.ref_name }}
  GH_TOKEN: ${{ github.token }}
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages via Pacman
        run: pacman -Sy; pacman --noconfirm -S git archiso python python-pygithub github-cli reflector p7zip  unzip zip
      - name: Build image
        run: mkarchiso -v iso/
      - name: Upload iso to the release
        run: |
          cd ./out
          mkdir iso_parts
          # split -d -b 2000M "$(ls *.iso)" iso_parts/"$(ls *.iso)"_part
          zip -s 1000m iso_parts/"$(ls *.iso)".zip "$(ls *.iso)"
          #7z -v1000m a iso_parts/"$(ls *.iso)".zip "$(ls *.iso)"
          md5sum iso_parts/* > iso_parts/md5sums.txt
          gh release upload ${{ github.event.release.tag_name }} ./iso_parts/* -R ${{ github.repository }}
